### ISSUE TITLE
Problems with Running via readme instructions.

### ISSUE THREAD

**Issue by krux02** [protontypes/openselery#100]
Readme specifies this line to run openselery:

```bash
TARGET_DIR=<target_repository> && env $(cat ~/.openselery/tokens.env) python3 selery.py --config $TARGET_DIR/selery.yml --directory $TARGET_DIR --result results
```

1. This is too complicated. When configuration files exist, everything necessary to run it should be ``./selery.py``, nothing else.

    - The program can parse on its own `tokens.env`
    - TARGET_DIR should be an argument, not an environment variable
    - current working directory (PWD environment variables) could be used by default
    - `--config $TARGET_DIR/selery.yml` and `--directory $TARGET_DIR` seems to be two redundant argument
2.  ``selery.py`` does not exist.

**Comment by Ly0n** [comment]
The project is evolving to fast at the moment so that we can not change all the instructions every time.
I made some changes to the master README to make it run on my local Ubuntu 20.04 without Docker.

Please let us all together improve the README on this branch together:
https://github.com/protontypes/openselery/tree/README_fine_tuning

If you are to long involved into a project you will get to much biased. It would be nice to get more feedback from new project contributors like @egebalkan or @ZeipsCode on that since they are fresh and know what a new user expects. It is the first impression that the project makes and should therefore be of high quality.

> This is too complicated. When configuration files exist, everything necessary to run it should be ./selery.py, nothing else.
Good point.

> TARGET_DIR should be an argument, not an environment variable
Good point.

> current working directory (PWD environment variables) could be used by default
I think this could be quite dangers. We should avoid making choices for users in OpenSelery. The side effects could be unpredictable.

> --config $TARGET_DIR/selery.yml and --directory $TARGET_DIR seems to be two redundant argument
No, we do have use cases where the configuration of OpenSelery is not inside the target folder. Let's also avoid defaults here since the side effects are unpredictable. User should make choices on purpose relating to OpenSelery. If the purpose in not 100% clear lets exit and do nothing.

**Comment by Ly0n** [comment]
@krux02 Is this solved by 4f2adcf99289b0380ac91350b2094dff48c0cb11 ?

**Comment by krux02** [comment]
I have to get to investigate how much this has improved. I did not get around to do it yet. But it is certainly not solved by the commit you linked. That one is to address a different problem, running OpenSelery locally from the source without installation.
